### ISSUE TITLE
Circle CI の導入

### ISSUE THREAD

**Issue by kasaharu** [kasaharu/annictor#1]
## TODO
- Circle CI 上でビルド、テストできるようにする

## メモ
- Circle CI で使うバージョンは circleci/node:8.9.4-stretch-browsers
    - `ng test` には Browser が必要になるため
- `ng test` は single-run で実行するようにする
- .circleci/config.yml に設定ミスがある場合は CircleCI のページの Workflows から確認できる
    - requires を設定するときはインデントに注意

**Comment by kasaharu** [comment]
下記 Circle CI が進めるサンプル
```
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
```
